### ISSUE TITLE
Errors on trigger

### ISSUE THREAD

**Issue by shraddharsh** [tomolimo/processmaker-server#8] opened 2018-07-13 11:01 UTC
Hi @tomolimo 
First of all thank you and appreciate your work on extending the functionality for GLPI.
We have figured a bug regarding triggers where in there were some _functions_ which were not declared as **static** while they were being accessed statically because of which triggers were not functional.
Up until now we have found bugs in the following files.
1. `/gulliver/system/class.g.php`
- array_merges
- toUpper

2. `workflow/engine/classes/class.system.php`
for functions like 
- getEmailConfiguration

I believe this bug is related to the following bug [#67](https://github.com/tomolimo/processmaker/issues/67)

Please Note: These changes have already been reflected in the upgraded version of processmaker.

**Comment by tomolimo** [comment] 2018-07-13 11:17
Hello @shraddharsh 

Thank you for your post.

I've in mind to upgrade PM server to latest version 3.2, But for that I need some times to be able to do extended tests of the new release, that's why I'm still with the 3.0.1.8

Regarding the https://github.com/tomolimo/processmaker/issues/67: I cannot figure out any root causes of the issues (seems like there are two issues in the same post) if I get no answers to my questions...

By the way, if you explain me the detailed steps to be able to reproduce your issue, and with the clues you gave me, I may be able to find a solution.

Thank you
Regards,
Tomolimo

PS: if you need to chat with me, just use the dedicated IRC channel #processmaker-glpi. Ss I'm not connected all the day on this channel, you may post an issue (or post in an existing issue) asking me to connect to the IRC.

**Comment by tomolimo** [comment] 2018-07-25 19:58
Hello,
As mentioned here https://github.com/tomolimo/processmaker/issues/72#issue-344448352, should I understand that you tested a process that is made for the 3.2 release of PM server, and that you tested it in the 3.0.1.8-RE-1.8 release?
If so, this process designed for 3.2 may use some functions/fixes that are not already existing in the 3.0.1.8-RE-1.8
Please explain me the steps to reproduce this issue, 
Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment] 2018-07-28 19:56
Closed as it is duplicated here https://github.com/tomolimo/processmaker/issues/72

**Closed as completed by tomolimo** 2018-07-28 19:56 UTC
